### ISSUE TITLE
Comment color in Dark High contrast is low contrast 

### ISSUE THREAD

**Issue by Jack-Works** [material-theme/vsc-material-theme#483] opened 2020-06-23 09:11 UTC
1. In the normal editor:

![image](https://user-images.githubusercontent.com/5390719/85385137-84f98400-b574-11ea-8f3f-9bdfb0f7857c.png)

![image](https://user-images.githubusercontent.com/5390719/85385151-8a56ce80-b574-11ea-820a-42760a0e6270.png)

2. In the diff editor

![image](https://user-images.githubusercontent.com/5390719/85385209-9a6eae00-b574-11ea-8640-b730290eb4a0.png)

![image](https://user-images.githubusercontent.com/5390719/85385238-a35f7f80-b574-11ea-9f9b-0eef66e0ff9f.png)

**Comment by equinusocio** [comment] 2020-06-23 09:44
Duplicate of:

https://github.com/material-theme/vsc-material-theme/issues/134
https://github.com/material-theme/vsc-material-theme/issues/173
https://github.com/material-theme/vsc-material-theme/issues/445

**Closed by equinusocio** 2020-06-23 09:44 UTC
