### ISSUE TITLE
Accent and syntax color "hot-swapping"

### ISSUE THREAD

**Issue by nedevel** [material-theme/vsc-material-theme#491] opened 2020-07-31 09:11 UTC
**Is your feature request related to a problem? Please describe.**
* When I use a light Material Theme, the accent color is `#80cbc4`.
* The yellow (classid/attribute names) and purple (storage) syntax colors look out of place in light theme - too strong and bright

**Describe the solution you'd like**
* An accent color designed to match each theme would be better
* Also optimising the light theme syntax colors for `storage` and `entity.other.attribute-name`/`entity.name.class`.

**Describe alternatives you've considered**
Open `settings.json` to write and update custom overrides every time I wish to change themes. And switching them on and off manually whenever I want to change from dark to light themes.

**Additional context**
<img src="https://user-images.githubusercontent.com/60514150/89025511-e6083a80-d31e-11ea-95aa-3ff05f3295a2.png" height="176">
<img src="https://user-images.githubusercontent.com/60514150/89025591-06d09000-d31f-11ea-9927-04c0739a4e6e.png" height="112">

EDIT: Previously this issue reported "When I switch from a Material Theme to another theme and back, the accent color is from the other theme. Each theme's JSON is missing an accent color.". This is by design, but will get a small fix as a result of this issue 👍

**Comment by equinusocio** [comment] 2020-07-31 10:19
> When I switch from a Material Theme to another theme and back, the accent color is from the other theme. Each theme's JSON is missing an accent color.

This is probably caused by other themes that set global workbench customizations. We're going to release a small fixe to apply Material Theme accents only for material themes variants, so other themes will not use our configurations, but we can't control other themes. You should ask the theme author to do the same.

> An accent color embedded in each theme would be much better than the current options

The default accent color for our themes is Teal, and with the fix mentioned above, our accents will be used only inside material theme variants.

**Comment by lmn8** [comment] 2020-07-31 10:20
Thanks for the reply. Is the correct solution for syntax colors to just change it and stick to one theme?

**Comment by equinusocio** [comment] 2020-07-31 10:22
I've updated my previous post.

**Comment by lmn8** [comment] 2020-07-31 10:46
Can I customise all Material dark themes in one set, and customise light ones in one set? Is there some kind of pattern contraption that lets me apply these changes to Community Material themes as well?

**Comment by lmn8** [comment] 2020-07-31 10:53
From what I can tell, https://github.com/material-theme/vsc-material-theme/issues/491#issuecomment-667059398 (above) is impossible currently, and could be a decent feature request in VSC.

**Comment by equinusocio** [comment] 2020-07-31 11:37
> Can I customize all Material dark themes in one set, and customize light ones in one set? Is there some kind of pattern contraption that lets me apply these changes to all, and add Community Material themes as well?

Nope, you have to apply the custom settings inside each group. With the fix that we'll release each time the accent is set all the changed settings are automatically applied to each material theme variant.

**Comment by lmn8** [comment] 2020-07-31 22:02
Alright, seems good to me. Adapting light theme to my tastes, I have changed `#7c4dff` to `#9c3eda` and to `#ffb62c` to `#e2931d`. You're free to adopt these colours for "lighter" theme and its Community variant, if you wish.

<img src="https://user-images.githubusercontent.com/60514150/89080467-d3bee880-d380-11ea-8dd2-504b689868d2.png" width="501">

Either way, this is a good theme pack and I appreciate the time that went into it!

**Comment by equinusocio** [comment] 2020-08-03 07:31
We think your suggested colors are a good balance between contrast and the material theme palette. I think we can update them, on the official extension (this one).

**Comment by lmn8** [comment] 2020-08-12 10:46
Microsoft may add theme selector patterns if this gets enough upvotes: https://github.com/microsoft/vscode/issues/103694

**Comment by equinusocio** [comment] 2020-08-12 10:58
Voted

**Comment by equinusocio** [comment] 2020-08-30 10:30
Closing this in favor of #494

**Closed by equinusocio** 2020-08-30 10:30 UTC
