### ISSUE TITLE
CSS text highlighting brakes within nth-.*()

### ISSUE THREAD

**Issue by Etsi0** [material-theme/vsc-material-theme#1308] opened 2024-10-02 18:21 UTC
### Description

When using `:not()` or `[hidden]` within an `nth-.*()` selector, the text highlighting breaks.
I'm not aware of anything else that brakes within an `nth-.*()` selector.

![image](https://github.com/user-attachments/assets/bb11c2f5-6cf9-4630-9c56-c95608ad7f84)

### Steps to reproduce

1. go to a `*.css` file
2. type in:
```css
:nth-child(:not([hidden]))
:nth-last-child(:not([hidden]))
:nth-last-of-type(:not([hidden]))
:nth-of-type(:not([hidden]))
```

### Extension Version

v34.7.5

### VSCode Version

v1.93.1

### Theme

Material Theme Palenight High Contrast

**Comment by equinusocio** [comment] 2024-10-14 08:25
Hello, this is a bug related to vscode scopes. The issue is present even with the default theme (despite is hard to see because they use a pale green color for numeric constants in css). Check this zoomed image:

![Screenshot 2024-10-14 at 10 24 51](https://github.com/user-attachments/assets/590cdf66-9d70-4852-98bd-c07d83cd2a5d)

You should report this issue to vscode team since we don't handle how colors are assigned to what, we just define the colors.

**Closed by equinusocio** 2024-10-14 08:25 UTC
Labels: bug
