### ISSUE TITLE
Add support to the new semanticHighlighting feature

### ISSUE THREAD

**Issue by vicjune** [material-theme/vsc-material-theme#458] opened 2020-03-10 13:12 UTC
**Describe the bug**
Some variables appear yellow instead of white without any particular reason.
This bug appeared with the VS Code February 2020 update.
Reloading VS Code doesn't fix the issue.

**To Reproduce**
1. Update VS Code
2. Put Material as Theme
3. Open a .ts file with a bunch of imports or variables

**Expected behavior**
Imports and variables should have the same color.

**Screenshots**
![Capture d’écran 2020-03-10 à 14 09 55](https://user-images.githubusercontent.com/19904059/76315377-d721dc80-62d8-11ea-8181-e43b9a268584.jpg)

**Comment by z4o4z** [comment] 2020-03-10 13:46
I've faced the same problem today, it happened after updating VS code:
![image](https://user-images.githubusercontent.com/9130301/76318300-9339d200-62ee-11ea-9c71-39003c228c7e.png)

**Comment by thesimpledesigners** [comment] 2020-03-10 13:58
Same issue here, the syntax highlight is different.

**Comment by Spittal** [comment] 2020-03-10 15:26
Mentioned a similar issue here: https://github.com/material-theme/vsc-material-theme/issues/439#issuecomment-597146802

**Comment by equinusocio** [comment] 2020-03-10 15:48
Just to be clear, that's not a bug. Vscode changed and improved how scoped are assigned to code elements, and it's a breaking change we don't support yet.

**Comment by sackda75** [comment] 2020-03-19 00:44
_"This will require long time to be added, meanwhile disable the new feature using editor.semanticHighlighting.enabled: false "_

Can anyone help me to do that ? I have no idea where it is. Thanks

**Comment by pilotocheg** [comment] 2020-03-19 10:10
> _"This will require long time to be added, meanwhile disable the new feature using editor.semanticHighlighting.enabled: false "_
> 
> Can anyone help me to do that ? I have no idea where it is. Thanks

press ctrl+shift+p on windows or cmd+shift+p on mac, type "settings" in the search field and choose "open settings (JSON)". Then add ```"editor.semanticHighlighting.enabled": false``` to json

**Comment by sackda75** [comment] 2020-03-19 11:27
> > _"This will require long time to be added, meanwhile disable the new feature using editor.semanticHighlighting.enabled: false "_
> > Can anyone help me to do that ? I have no idea where it is. Thanks
> 
> press ctrl+shift+p on windows or cmd+shift+p on mac in opened editor, type "settings" in the search field and choose "open settings (JSON)". Then add `"editor.semanticHighlighting.enabled": false` to json

Thank you pilotocheg. I did it and i found out that it's already false 
![Capture1](https://user-images.githubusercontent.com/59691396/77062355-096bc200-69dc-11ea-8f79-5e0ed6b7799d.PNG)

But in the defaultSettings.json it's "true" but we can not change it (read only) 
![Capture12](https://user-images.githubusercontent.com/59691396/77062528-52bc1180-69dc-11ea-8d5d-bc7728314379.PNG)

Since VS Code has updated, some colors have gone : (
- { StyleSheet, View } were yellow
- styles was red
- etc
![Capture123](https://user-images.githubusercontent.com/59691396/77062797-dd9d0c00-69dc-11ea-82ce-29e1e485c665.PNG)

**Comment by equinusocio** [comment] 2020-04-23 18:53
Ref #472

**Closed by equinusocio** 2020-04-23 18:54 UTC
Labels: Enhancement, Scheme, To investigate
